name: dotnet build
description: Builds a .NET project and all of its dependencies.

inputs:
  asset-version-number:
    required: false
    description: The version number for the artifact
  asset-name:
    required: false
    description: The name for the artifact
  asset-publish:
    required: false
    default: "false"
    description: Publish artifact as asset on workflow
  al-version-number:
    required: true
    description: The version number of the corresponding AL Language
  al-asset-uri:
    required: true
    description: The asset uri for retrieving the VSIXPackage/NuGetPackage of the AL Language
  al-asset-type:
    required: true
    description: The asset type, VSIXPackage or NuGetPackage
  al-latest:
    default: "false"
    required: false
    description: Set build as Latest version of the AL Language
  al-prerelease:
    default: "false"
    required: false
    description: Set build as Pre-Release version of the AL Language

runs:
  using: composite
  steps:
    - name: Get AL Language platform artifacts
      id: get-platform-artifacts
      uses: ./.github/actions/platform-artifacts
      with:
        version-number: ${{ inputs.al-version-number }}
        asset-uri: ${{ inputs.al-asset-uri }}
        asset-type: ${{ inputs.al-asset-type }}
        target-path: ALLanguage

    - name: Populate Feature Flags
      id: get-feature-flags
      uses: ./.github/actions/feature-flags
      with:
        version-number: ${{ inputs.al-version-number }}

    - name: Get Target Framework
      id: get-target-framework
      uses: ./.github/actions/target-framework
      with:
        asset-type: ${{ inputs.al-asset-type }}
        version-number: ${{ inputs.al-version-number }}

    - name: Normalize version number
      id: normalize-version
      shell: pwsh
      run: |
        $input = "${{ inputs.asset-version-number }}"
        if ([string]::IsNullOrWhiteSpace($input)) {
          $normalized = "1.0.0.0"
        }
        else {
          $normalized = $input.TrimStart("v")
        }

        echo "Normalized version: $normalized"
        echo "normalized-asset-version=$normalized" >> $env:GITHUB_OUTPUT

    - name: Get version from Microsoft.Dynamics.Nav.CodeAnalysis.dll
      id: get-codeanalysis-version
      shell: pwsh
      run: |
        $filePath = "./ALLanguage/Microsoft.Dynamics.Nav.CodeAnalysis.dll"

        $asm = [System.Reflection.Assembly]::LoadFrom($filePath)
        $attr = $asm.GetCustomAttributes([System.Reflection.AssemblyFileVersionAttribute], $false)
        if ($attr.Count -gt 0) {
            $version = $attr[0].Version
        } else {
            $version = $asm.GetName().Version.ToString()
        }

        Write-Host "CodeAnalysis.dll version: $version"
        echo "codeanalysis-version=$version" >> $env:GITHUB_OUTPUT

    - name: Build
      shell: pwsh
      run: >
        dotnet build BusinessCentral.LinterCop
        --configuration Release
        --framework ${{ steps.get-target-framework.outputs.target-framework }}
        -p:FeatureFlags=${{ steps.get-feature-flags.outputs.feature-flags }}
        -p:Product="BusinessCentral.LinterCop"
        -p:Version=${{ steps.normalize-version.outputs.normalized-asset-version }}
        -p:InformationalVersion=${{ steps.normalize-version.outputs.normalized-asset-version }}
        -p:AssemblyTitle="AL-${{ inputs.al-version-number }}"
        -p:MSBuildAssemblyNameOverride="BusinessCentral.LinterCop.AL-${{ inputs.al-version-number }}" # TODO: this naming needs to account for prerelease and latest
        -p:FileVersion=${{ steps.get-codeanalysis-version.outputs.codeanalysis-version }}

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/BusinessCentral.LinterCop.Test/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Test
      shell: pwsh
      run: dotnet test BusinessCentral.LinterCop.Test /p:FeatureFlags=${{ steps.get-feature-flags.outputs.feature-flags }}

    - name: Upload build artifact
      id: upload-build-asset
      uses: actions/upload-artifact@v4
      if: ${{ inputs.asset-publish == 'true' }}
      with:
        name: ${{ inputs.asset-name }}
        path: BusinessCentral.LinterCop/bin/Release/${{ steps.get-target-framework.outputs.target-framework }}/BusinessCentral.LinterCop.dll # TODO: this needs to now be dynamically evaluated based on the name change above
        compression-level: 0 # no compression

    ### Upload Asset as Latest
    - name: Upload build artifact (Latest)
      id: upload-build-asset-latest
      uses: actions/upload-artifact@v4
      if: ${{ inputs.asset-publish == 'true' && inputs.al-latest == 'true' }}
      with:
        name: BusinessCentral.LinterCop.dll
        path: BusinessCentral.LinterCop/bin/Release/${{ steps.get-target-framework.outputs.target-framework }}/BusinessCentral.LinterCop.dlll # TODO: this needs to now be dynamically evaluated based on the name change above
        compression-level: 0 # no compression

    ### Upload Asset as Pre-Release
    - name: Upload build artifact (Pre-Release)
      id: upload-build-asset-prerelease
      uses: actions/upload-artifact@v4
      if: ${{ inputs.asset-publish == 'true' && inputs.al-prerelease == 'true' }}
      with:
        name: BusinessCentral.LinterCop.AL-PreRelease.dll
        path: BusinessCentral.LinterCop/bin/Release/${{ steps.get-target-framework.outputs.target-framework }}/BusinessCentral.LinterCop.dlll # TODO: this needs to now be dynamically evaluated based on the name change above
        compression-level: 0 # no compression
